name: Publish Harbor Image (Release)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  push-to-harbor:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-harbor
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get SDK version
        id: get_version
        run: echo "version=$(awk -F'"' '/^version = / {print $2}' pyproject.toml)" >> $GITHUB_OUTPUT

      - name: Get short commit SHA
        id: get_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to Atlan Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: registry.atlan.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Log in to Chainguard Container Registry
        uses: docker/login-action@v3
        with:
          registry: cgr.dev
          username: ${{ secrets.CHAINGUARD_USERNAME }}
          password: ${{ secrets.CHAINGUARD_PASSWORD }}

      - name: Build, scan, and push image to Harbor
        id: harbor_docker_build
        uses: ./.github/actions/secure-build-push-apps
        with:
          branch: main
          snyk-token: ${{ secrets.SNYK_TOKEN_BU_APPS }}
          snyk-ghcr-integration-id: ${{ secrets.SNYK_GHCR_INTEGRATION_ID }}
          snyk-docker-integration-id: ${{ secrets.SNYK_DOCKER_INTEGRATION_ID }}
          snyk-integration-id: ${{ secrets.SNYK_INTEGRATION_ID }}
          snyk-org-id: ${{ secrets.SNYK_ORG_ID }}
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            registry.atlan.com/public/application-sdk:main-latest
            registry.atlan.com/public/application-sdk:main-${{ steps.get_version.outputs.version }}
            registry.atlan.com/public/application-sdk:sha-${{ steps.get_sha.outputs.sha }}
          build-args: |
            ACCESS_TOKEN_USR=$GITHUB_ACTOR
            ACCESS_TOKEN_PWD=${{ secrets.ORG_PAT_GITHUB }}
          github-token: ${{ secrets.ORG_PAT_GITHUB }}
        env:
          DOCKER_CLIENT_TIMEOUT: 600
          COMPOSE_HTTP_TIMEOUT: 600
